# Generated by Django 2.0.6 on 2019-02-21 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwApp', '0002_auto_20190221_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='', max_length=200)),
                ('model', models.CharField(default='', max_length=200)),
                ('year', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
